version: 2
jobs:
  build:
    docker:
      - image: tethik/xelatex:latest
    steps:
      - checkout
      - run: make 
      - store_artifacts:
          path: cv.pdf


workflows:
  version: 2
  build:
    jobs:
      - build
    filters:
      branches:
        only: 
          - circleci          
          - master


