version: 2
jobs:
  build:
    docker:
      - image: tethik/xelatex:latest
    steps:
      - checkout
      - run: make 
      - persist_to_workspace:
          root: .
          paths:
            - cv.pdf
      # - store_artifacts:
      #     path: cv.pdf
  deploy:
    docker:
      - image: circleci/node:8.9
    steps:
      - checkout
      - attach_workspace:
          at: .      
      - run: .circleci/deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: 
                - circleci          
                - develop
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: 
                - develop



